### ISSUE TITLE
Two of the hyperlinks in the Congratulations section are not correct

### ISSUE THREAD

**Issue by alan-leslie** [googlecodelabs/maps-platform-101-android#8]
Two of the hyperlinks in the Congratulations section are not correct
The one for "Places SDK for Android" results in a 404  - maybe it should be something like https://developers.google.com/maps/documentation/places/android-sdk/overview
The one for "android-place-ktx" points to the map ktx. It should point to https://github.com/googlemaps/android-places-ktx

**Comment by arriolac** [comment]
The fix for this will be live shortly. Thanks for reporting!
